name: QA Automation Pipeline

on:
  push:
    branches: [ main ]
  pull_request:

jobs:

  ui-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install
          npx playwright install --with-deps

      - name: Run UI tests
        run: |
          cd ui-tests
          npx playwright test

      - name: Upload UI Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ui-playwright-report
          path: ui-tests/playwright-report/

  api-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run API tests
        run: |
          cd api-tests
          npx playwright test

      - name: Upload API Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-playwright-report
          path: api-tests/playwright-report/

  load-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          cd load-tests
          pip install -r requirements.txt

      - name: Run load tests
        run: |
          cd load-tests
          locust -f locustfile.py --headless -u 1 -r 1 -t 10s --only-summary